name: Prettier Check

on:
    pull_request:
    push:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Install dependencies
              run: npm install

            - name: Run Prettier check
              run: npm run format:check
